// Generates docs/AGENTS.md, docs/GO-TO-MARKET.md and the skill's agent reference from the source data.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { AGENTS, PLANS } from "../lib/agent-catalog";
import { CHANNELS, LAUNCH_PLAN, READINESS, SEGMENTS } from "../lib/gtm";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const nm = (id: string) => (id === "all" ? "All agents" : AGENTS.find((a) => a.id === id)?.name ?? id);
const bullets = (xs: string[]) => xs.map((x) => `- ${x}`).join("\n");
const header = "<!-- Generated by `npm run docs` from lib/agent-catalog.ts and lib/gtm.ts — edit those files, not this one. -->\n\n";

const agentsMd = header + `# Chimera AEC — agent catalog

${AGENTS.length} specialist agents, ${AGENTS.reduce((s, a) => s + a.skills.length, 0)} engineering skills. Each agent runs inside the multi-agent workflow, is available through \`POST /api/v1/analyze\` and is callable from the Claude Skill.

| Agent | Discipline | Plan | What it does |
|---|---|---|---|
${AGENTS.map((a) => `| [${a.name}](#${a.id}) | ${a.discipline} | ${a.tier}+ | ${a.tagline} |`).join("\n")}

${AGENTS.map((a) => `## ${a.name} <a id="${a.id}"></a>

**ID:** \`${a.id}\` · **Discipline:** ${a.discipline} · **Plan:** ${a.tier}+

${a.description}

**Business value:** ${a.valueProp}

**Skills & methods**
${bullets(a.skills)}

**Inputs**
${bullets(a.inputs)}

**Outputs**
${bullets(a.outputs)}

**Standards:** ${a.standards.join("; ")}

**Collaborates with:** ${a.handoffs.map((h) => `${nm(h.to)} (${h.what})`).join("; ")}

**Who buys it:** ${a.buyers.join(", ")}

**Scope & limits:** ${a.limits}
`).join("\n")}`;

const gtmMd = header + `# Where to sell Chimera AEC agents to businesses

## 1. Buyer segments

| Segment | Pain | Offer | Lead agents | Economic buyer |
|---|---|---|---|---|
${SEGMENTS.map((s) => `| ${s.segment} | ${s.pain} | ${s.offer} | ${s.agents.map(nm).join(", ")} | ${s.buyer} |`).join("\n")}

## 2. Channels

> Programmes and URLs are real, but eligibility, fees and review times change. Verify current terms with each provider before applying.

${CHANNELS.map((c) => `### ${c.name}
*${c.type}* · effort **${c.effort}** · time to revenue **${c.timeToRevenue}**${c.url ? ` · ${c.url}` : ""}

- **Reaches:** ${c.who}
- **How to sell:** ${c.howToSell}
- **Package as:** ${c.packageAs}
- **Lead agents:** ${c.agents.map(nm).join(", ")}
`).join("\n")}
## 3. Packaging & pricing (suggested — validate in pilots)

| Plan | Price | For | Includes |
|---|---|---|---|
${PLANS.map((p) => `| ${p.tier} | ${p.price} ${p.unit} | ${p.for} | ${p.includes.join("; ")} |`).join("\n")}

Other models: per project/tender, metered API runs, per m² GFA, white-label licence.

## 4. Launch plan

${LAUNCH_PLAN.map((p) => `### ${p.phase} (${p.weeks})\n${bullets(p.actions)}`).join("\n\n")}

## 5. Before you sell

${READINESS.map((r) => `- **${r.item}** — ${r.why}`).join("\n")}

## 6. What is already sellable in this repo

- **SaaS workspace** (\`aec/\`): authentication, projects, all agents, BIM/IFC, compliance, reports.
- **Metered API**: keys in Settings → API keys; \`GET /api/v1/agents\` (public catalog), \`POST /api/v1/analyze\` (runs agents, ${"5,000"} runs/key/month).
- **Claude Skill**: \`aec/skills/chimera-aec-agents/\` — distribute to Claude users; they pay for the API key.
`;

const ref = `# Agent IDs\n\n${AGENTS.map((a) => `- \`${a.id}\` — **${a.name}** (${a.discipline}): ${a.tagline} Returns: ${a.resultKeys.length ? a.resultKeys.map((k) => `\`${k}\``).join(", ") : "operations data (app only)"}.`).join("\n")}\n`;

fs.writeFileSync(path.join(root, "docs/AGENTS.md"), agentsMd);
fs.writeFileSync(path.join(root, "docs/GO-TO-MARKET.md"), gtmMd);
fs.writeFileSync(path.join(root, "skills/chimera-aec-agents/references/agents.md"), ref);
console.log("Wrote docs/AGENTS.md, docs/GO-TO-MARKET.md, skills/chimera-aec-agents/references/agents.md");
