"""Initial (all-pending) international exposure register.

These entries define what must be measured. They contain no values; each
becomes "measured" only when its owner links a retrieved observation.
"""

from __future__ import annotations

from .exposure import ExposureEntry

SEED: list[ExposureEntry] = [
    ExposureEntry("EXP-01", "Remittance dependence and corridor concentration", "remittances",
                  ["Gulf Cooperation Council states", "Malaysia", "India", "other"],
                  "personal remittances / GDP; share by source corridor", "percent", "23C",
                  ["nrb", "knomad", "nso_nepal"], ["S01", "S04", "S06", "S10"],
                  concentration_question="What share of inflows comes from the top 3 corridors?"),
    ExposureEntry("EXP-02", "Migrant workers by destination", "migrant_employment",
                  ["Qatar", "Saudi Arabia", "UAE", "Kuwait", "Malaysia", "Republic of Korea", "Japan"],
                  "new labour permits by destination; estimated migrant stock", "persons", "23A",
                  ["dofe", "glmm"], ["S01", "S06", "S10"]),
    ExposureEntry("EXP-03", "Goods trade concentration with India", "transit_and_logistics", ["India"],
                  "India share of goods imports and exports", "percent", "04A",
                  ["customs_nepal", "tepc"], ["S02", "S10"]),
    ExposureEntry("EXP-04", "Third-country trade transit via Indian ports", "transit_and_logistics",
                  ["India"], "share of third-country imports transiting Kolkata/Haldia/Visakhapatnam", "percent",
                  "21B", ["customs_nepal", "wb_lpi"], ["S02", "S10"]),
    ExposureEntry("EXP-05", "Petroleum import dependence and supplier", "fuel_prices", ["India"],
                  "petroleum products share of imports; supplier share", "percent", "22A",
                  ["noc_nepal", "customs_nepal"], ["S01", "S02", "S10"]),
    ExposureEntry("EXP-06", "Cross-border electricity trade", "electricity_trade", ["India", "Bangladesh"],
                  "electricity exports and imports by counterparty and season", "GWh", "22B",
                  ["nea", "cea_india"], ["S02", "S05", "S09"]),
    ExposureEntry("EXP-07", "Glacier- and snow-fed share of hydropower", "hydro_generation", ["shared basins"],
                  "share of generation capacity in glacier/snow-fed basins", "percent", "25A",
                  ["icimod", "nea"], ["S05", "S09"]),
    ExposureEntry("EXP-08", "Tourism source markets", "tourism_demand",
                  ["India", "China", "United States", "United Kingdom", "other"],
                  "arrivals share by origin; travel receipts / GDP", "percent", "12C",
                  ["tourism_ministry", "nrb"], ["S01", "S04", "S10"]),
    ExposureEntry("EXP-09", "Air connectivity through Gulf hubs", "aviation_connectivity",
                  ["UAE", "Qatar", "India"], "share of international seats via Gulf and Indian hubs", "percent",
                  "19C", ["caan"], ["S01", "S10"],
                  notes="CAAN statistics may not include seat capacity; commercial schedule data may be needed."),
    ExposureEntry("EXP-10", "NPR-INR peg and INR/USD exposure", "exchange_rate", ["India"],
                  "share of trade invoiced in INR vs USD; INR/USD volatility", "percent", "20B",
                  ["nrb", "rbi"], ["S02", "S03", "S10"]),
    ExposureEntry("EXP-11", "External public debt by creditor and currency", "external_financing",
                  ["World Bank (IDA)", "ADB", "bilateral creditors"], "external debt share by creditor/currency",
                  "percent", "20C", ["pdmo", "wb_ids"], ["S04", "S08", "S10"]),
    ExposureEntry("EXP-12", "FDI by source country", "external_financing", ["all sources"],
                  "FDI stock/inflows by source", "percent", "12B", ["nrb", "doind"], ["S03", "S04"]),
    ExposureEntry("EXP-13", "Loss of LDC-specific trade preferences", "trade_preferences",
                  ["European Union", "United Kingdom", "other preference-granting members"],
                  "exports benefiting from LDC-only preferences / total exports", "percent", "21A",
                  ["wto", "undesa_ldc", "eu_trade"], ["S08"]),
    ExposureEntry("EXP-14", "Digital-service exports exposed to AI substitution", "digital_services_demand",
                  ["United States", "Europe", "Australia"], "ICT/BPO exports by segment and destination",
                  "USD_current", "08A", ["nrb", "unctadstat"], ["S07"]),
    ExposureEntry("EXP-15", "Fertiliser import dependence", "agricultural_output", ["India", "China", "other"],
                  "imported share of fertiliser use; supplier concentration", "percent", "21D",
                  ["customs_nepal", "fao_stat"], ["S02", "S10"]),
    ExposureEntry("EXP-16", "Medicine and medical-supply import dependence", "transit_and_logistics",
                  ["India", "other"], "imported share of pharmaceutical consumption", "percent", "21D",
                  ["customs_nepal", "mohp"], ["S02", "S10"]),
    ExposureEntry("EXP-17", "Correspondent banking concentration", "financial_compliance", ["USD/INR correspondents"],
                  "number of active correspondent relationships; share via top 3", "ratio", "20D",
                  ["nrb", "bis_bank"], ["S03", "S10"]),
    ExposureEntry("EXP-18", "FATF/APG standing", "financial_compliance", ["FATF", "APG"],
                  "current listing status and open action items", "index", "20E", ["fatf", "apg"], ["S10"]),
    ExposureEntry("EXP-19", "Imported technology subject to export controls", "technology_costs",
                  ["United States", "China", "EU"], "share of ICT capital imports under controlled categories",
                  "percent", "19B", ["bis_us", "un_comtrade"], ["S03"]),
    ExposureEntry("EXP-20", "Transboundary flood exposure", "infrastructure_damage", ["India", "China (Tibet)"],
                  "capital stock in cross-border flood and GLOF hazard zones", "USD_current", "25C",
                  ["ndrrma", "icimod", "thinkhazard"], ["S05", "S10"]),
]
