"""Electricity balance and export-versus-domestic-use comparison.

Balance (one period, GWh):
    generation + imports = domestic_consumption + exports + losses (+ own use)

The opportunity-cost comparison deliberately takes every price and cost as an
explicit argument. There are no default numbers: all values must come from
the observation store or a registered assumption.
"""

from __future__ import annotations

from dataclasses import dataclass

from .accounts import IdentityCheck


@dataclass(frozen=True)
class ElectricityBalance:
    period: str
    generation_gwh: float
    imports_gwh: float
    domestic_consumption_gwh: float
    exports_gwh: float
    losses_gwh: float
    own_use_gwh: float = 0.0
    rel_tol: float = 1e-6

    def checks(self) -> list[IdentityCheck]:
        supply = self.generation_gwh + self.imports_gwh
        use = self.domestic_consumption_gwh + self.exports_gwh + self.losses_gwh + self.own_use_gwh
        return [IdentityCheck("electricity_balance", supply, use, "GWh", self.rel_tol)]

    @property
    def loss_rate(self) -> float:
        supply = self.generation_gwh + self.imports_gwh
        return self.losses_gwh / supply if supply else 0.0


@dataclass(frozen=True)
class MarginalUseComparison:
    """Value per marginal GWh, in one money unit per GWh."""

    export_price_per_gwh: float
    export_transmission_cost_per_gwh: float
    domestic_value_added_per_gwh: float  # national VA generated by an industry using 1 GWh
    domestic_tariff_per_gwh: float  # what the industry pays the utility
    domestic_grid_cost_per_gwh: float  # incremental distribution/reliability cost
    unit: str

    def export_net_value(self) -> float:
        return self.export_price_per_gwh - self.export_transmission_cost_per_gwh

    def domestic_net_value(self) -> float:
        # National VA already includes the utility's revenue from the tariff (it is
        # the industry's intermediate cost but the utility's output). Grid cost is
        # a real resource cost.
        return self.domestic_value_added_per_gwh + self.domestic_tariff_per_gwh - self.domestic_grid_cost_per_gwh

    def summary(self) -> dict:
        e, d = self.export_net_value(), self.domestic_net_value()
        return {
            "export_net_value_per_gwh": e,
            "domestic_net_value_per_gwh": d,
            "difference_domestic_minus_export": d - e,
            "unit": self.unit,
            "caveat": (
                "Static comparison; ignores demand constraints, seasonal mismatch, "
                "capital costs of new industry and foreign-exchange effects."
            ),
        }
