// Product catalog for the specialist agents: what each one does, the skills
// (methods) it runs, inputs/outputs, standards, collaboration hand-offs, who
// buys it, and how it is packaged. Used by the catalog page, the public API
// (/api/v1/agents) and the Claude Skill.

export type Tier = "Starter" | "Professional" | "Enterprise";

export interface AgentSpec {
  id: string;
  name: string;
  discipline: string;
  tagline: string;
  description: string;
  skills: string[];        // concrete methods the agent executes
  inputs: string[];
  outputs: string[];
  standards: string[];
  handoffs: { to: string; what: string }[];
  buyers: string[];        // business roles that pay for it
  valueProp: string;       // the business outcome
  tier: Tier;              // lowest plan that includes it
  resultKeys: string[];    // sections of the workflow result this agent owns (API)
  limits: string;          // honest scope statement
}

export const AGENTS: AgentSpec[] = [
  {
    id: "intake", name: "Intake & Brief", discipline: "Management", tier: "Starter",
    tagline: "Turns a site and a client brief into an engineering-ready design basis.",
    description: "Normalises site geometry, occupancy, climate, hazards, budget and performance targets; derives GFA, NLA, height, occupant load, risk category and importance factor; generates a parametric starting scheme.",
    skills: ["Occupancy classification (IBC Ch. 3)", "Risk category & importance factor (ASCE 7-22 Table 1.5-1)", "Occupant-load estimation", "Parametric grid / core / floor-height generation", "City presets for climate & hazard data"],
    inputs: ["Site width & depth", "Building type & storeys", "City / jurisdiction", "Hazard data (wind, Ss/S1, snow, rain, flood, wildfire)", "Budget, EUI & carbon targets", "Priorities (cost, carbon, area, daylight, speed)"],
    outputs: ["Design basis", "Derived areas & occupancy", "Initial parametric scheme"],
    standards: ["IBC 2024 Ch. 3", "ASCE 7-22 Ch. 1"],
    handoffs: [{ to: "all", what: "Normalised brief and derived quantities" }],
    buyers: ["Developers", "Architects (feasibility)", "Owner's representatives"],
    valueProp: "Feasibility in minutes instead of weeks; consistent design basis for every discipline.",
    resultKeys: ["derived", "params"], limits: "Hazard presets are regional averages; site-specific hazard data should replace them.",
  },
  {
    id: "codes", name: "Code Intelligence", discipline: "Compliance", tier: "Starter",
    tagline: "Finds the applicable codes, the right editions, and checks every clause.",
    description: "Resolves applicable standards by jurisdiction, classification and system, controls code editions (current / superseded / pending, project pins) and aggregates clause-level findings with requirement, clause, evidence, value/limit and PASS/FAIL.",
    skills: ["Jurisdiction → standards resolution (US, UK, AU, NZ, CA, SG)", "Edition/version control with project pinning", "Clause-level finding aggregation", "Proxy-method labelling where a local clause is not encoded", "CSV compliance report export"],
    inputs: ["Jurisdiction", "Occupancy & height", "Structural material/system", "Standards library"],
    outputs: ["Applicable code list with editions", "~60 clause-level findings", "Version-control warnings"],
    standards: ["IBC, ASCE 7, ACI 318, AISC 360/341, NDS, NFPA 13/14/72/285, ASHRAE 90.1/62.1/55, NEC, IPC, ADA", "Eurocodes & Approved Documents (UK)", "NCC & AS/NZS (AU/NZ)", "NBC / CSA (CA)"],
    handoffs: [{ to: "all", what: "Applicable editions and edition warnings" }],
    buyers: ["Engineering consultancies", "Plan-review / permitting authorities", "Code consultants"],
    valueProp: "Fewer RFIs and permit comments; an auditable trail from requirement to evidence.",
    resultKeys: ["codes", "findings"], limits: "Decision support; confirm against the licensed adopted edition and local amendments.",
  },
  {
    id: "architecture", name: "Architecture", discipline: "Architecture", tier: "Starter",
    tagline: "Plans the core and negotiates space with structure, fire and MEP.",
    description: "Sizes the core for stairs, lifts and risers; receives constraints from fire (exits), structure (wall thickness) and MEP (riser and plant areas); reports net-area impact of every design change.",
    skills: ["Core area planning", "Net lettable area & efficiency", "Lift count estimation", "Impact reporting on design changes"],
    inputs: ["Brief", "Fire egress requirements", "MEP riser/plant areas"],
    outputs: ["Core dimensions", "NLA / efficiency", "Design-change log"],
    standards: ["IBC Ch. 10 (via Fire agent)"],
    handoffs: [{ to: "structural", what: "Core geometry" }, { to: "cost", what: "Area schedule" }],
    buyers: ["Architects", "Developers"],
    valueProp: "Protects saleable area by surfacing the cost of every engineering decision immediately.",
    resultKeys: ["derived", "changes"], limits: "Rectilinear plates and central cores only.",
  },
  {
    id: "geotech", name: "Geotechnical", discipline: "Geotechnical", tier: "Professional",
    tagline: "Reads borehole logs and turns them into design parameters.",
    description: "Interprets borehole/CPT logs into a soil profile; estimates shear-wave velocity and Vs30 → site class; computes bearing capacity, raft settlement (two stress-distribution methods) and liquefaction triggering.",
    skills: ["Imai (1977) Vs–SPT correlation, Vs30", "ASCE 7-22 Table 20.2-1 site class (incl. BC/CD/DE)", "Vesić/Meyerhof bearing capacity", "2:1 and Boussinesq (Newmark) settlement with 1-D consolidation", "Youd et al. (2001) liquefaction triggering with fines correction"],
    inputs: ["Borehole logs (layers, SPT N, γ, cu, φ, Es, Cc, e0, fines)", "Groundwater level", "Founding depth"],
    outputs: ["Site class & Vs30", "qult / qall", "Settlement", "Liquefaction FS by depth"],
    standards: ["ASCE 7-22 Ch. 20 & §11.8", "EN 1997-1", "IBC §1803/1806"],
    handoffs: [{ to: "seismic", what: "Site class → Fa/Fv, SDS/SD1" }, { to: "structural", what: "Allowable bearing, GWL, liquefaction" }],
    buyers: ["Geotechnical consultancies", "Contractors (tender)", "Developers (due diligence)"],
    valueProp: "Early ground-risk visibility before committing to a foundation strategy.",
    resultKeys: ["geotech"], limits: "Correlation-based screening; confirm with site investigation and lab testing.",
  },
  {
    id: "structural", name: "Structural", discipline: "Structural", tier: "Professional",
    tagline: "Selects the lateral system and designs the frame with a finite-element solver.",
    description: "Compares eight lateral systems with FE analysis and ranks them on cost, carbon, area and code path; builds the planar FE model; runs gravity and lateral load cases; checks columns, punching shear and slab depth; iterates member sizes with the seismic agent until drift and strength converge.",
    skills: ["2D direct-stiffness frame solver (banded LDLᵀ)", "Automatic system selection (ASCE 7-22 Table 12.2-1)", "Gravity design: ACI 318-19 §22.4.2 columns, §22.6.5.2 punching, Table 8.3.1.1 slabs", "Design-iteration loop (core thickening, outriggers, column/f'c upgrades)", "Structural quantities (concrete, rebar, steel, timber, formwork)"],
    inputs: ["Parametric scheme", "Loads", "Site class & seismic parameters"],
    outputs: ["Selected system", "Member sizes", "Story forces & drifts", "Utilisations", "Quantities"],
    standards: ["ASCE 7-22", "ACI 318-19", "AISC 360-22", "NDS 2024"],
    handoffs: [{ to: "architecture", what: "Core/column size changes" }, { to: "cost", what: "Quantities" }, { to: "bim", what: "Member geometry" }],
    buyers: ["Structural engineers", "Design-build contractors", "Developers"],
    valueProp: "Scheme-design structure in minutes with a defensible system choice.",
    resultKeys: ["structure", "selection", "iterations"], limits: "Planar equivalent frame with rigid diaphragm; final design needs a 3D model.",
  },
  {
    id: "seismic", name: "Seismic", discipline: "Structural", tier: "Professional",
    tagline: "Earthquake demand, dynamics and performance assessment.",
    description: "Builds the design spectrum, solves modes, runs ELF and CQC response-spectrum analysis with scaling, checks drift, P-Δ and torsion, then estimates performance with a capacity-spectrum pushover and response-history analysis.",
    skills: ["Site coefficients & design spectrum (ASCE 7-22 §11.4)", "Jacobi eigen-analysis, mass participation", "ELF (§12.8) and CQC RSA with §12.9.1.4 scaling", "Drift (Table 12.12-1), P-Δ (§12.8.7), torsion (Table 12.3-1)", "Capacity-spectrum pushover (FEMA 440)", "Newmark MDOF time-history with spectrum-scaled record + nonlinear ESDOF"],
    inputs: ["Ss, S1, site class, risk category", "Stiffness & mass from the FE model"],
    outputs: ["Periods & mode shapes", "Base shear", "Drift/P-Δ/torsion checks", "Performance level", "Ductility demand"],
    standards: ["ASCE 7-22 Ch. 11–12, 16", "EN 1998-1", "NZS 1170.5", "AS 1170.4"],
    handoffs: [{ to: "structural", what: "Drift failures → stiffening requests" }],
    buyers: ["Structural engineers in seismic regions", "Insurers & lenders (risk)", "Hospitals & essential facilities"],
    valueProp: "Performance-based insight at scheme stage instead of after detailed design.",
    resultKeys: ["seismic", "structure"], limits: "Pushover/time-history are simplified (bilinear ESDOF); not a fibre-section NLTHA.",
  },
  {
    id: "wind", name: "Wind Engineering", discipline: "Structural", tier: "Professional",
    tagline: "Wind loads, sway, occupant comfort and façade pressures.",
    description: "Computes velocity pressures, the flexible-building gust-effect factor, story forces, serviceability drift, 10-year accelerations, vortex-shedding risk, C&C façade pressures and a pedestrian-comfort screen.",
    skills: ["ASCE 7-22 Eq. 26.10-1 velocity pressure", "§26.11.5 gust-effect factor (resonant response)", "Along-wind acceleration (C26.11)", "Vortex-shedding screening (EN 1991-1-4 Annex E)", "C&C zone pressures", "Lawson pedestrian comfort"],
    inputs: ["Basic wind speed, exposure", "Geometry", "Fundamental frequency & damping"],
    outputs: ["Story forces", "Roof drift", "Peak acceleration", "Façade pressure map", "Comfort categories"],
    standards: ["ASCE 7-22 Ch. 26–27, 30", "EN 1991-1-4", "AS/NZS 1170.2", "ISO 10137"],
    handoffs: [{ to: "structural", what: "Wind story forces" }, { to: "facade", what: "Design pressures" }],
    buyers: ["Tall-building developers", "Façade consultants", "Structural engineers"],
    valueProp: "Tells you early whether a wind-tunnel test and damping will be needed.",
    resultKeys: ["wind"], limits: "Screening only; does not replace CFD or wind-tunnel testing.",
  },
  {
    id: "foundation", name: "Foundation Optimiser", discipline: "Geotechnical", tier: "Professional",
    tagline: "Compares five foundation systems on capacity, settlement, cost, carbon and time.",
    description: "Designs pads, raft, bored piles, barrettes and piled raft for the real column loads; designs piles with α/β shaft friction ignoring liquefiable layers; ranks the options.",
    skills: ["Pad and raft sizing", "Pile design (α-method clay, β-method sand, end bearing)", "Piled-raft load sharing", "Multi-criteria ranking (cost, carbon, duration, settlement)"],
    inputs: ["Column and total service loads", "Geotechnical profile"],
    outputs: ["Option comparison", "Selected foundation", "Pile count & length"],
    standards: ["IBC §1808–1810", "EN 1997-1", "AS 2159"],
    handoffs: [{ to: "cost", what: "Foundation cost & carbon" }, { to: "construction", what: "Duration & rig needs" }],
    buyers: ["Contractors", "Developers", "Geotechnical engineers"],
    valueProp: "Foundations are often 5–15 % of cost; picking the right system early de-risks the budget.",
    resultKeys: ["geotech"], limits: "Group effects and negative skin friction simplified.",
  },
  {
    id: "hvac", name: "HVAC", discipline: "Mechanical", tier: "Professional",
    tagline: "Loads, ventilation, plant, ducts and thermal comfort.",
    description: "Zoned cooling/heating loads, ASHRAE 62.1 outdoor air, N+1 chiller/boiler/heat-pump plant, AHU and duct sizing, plant and riser areas and ISO 7730 PMV/PPD comfort.",
    skills: ["Component cooling/heating loads by zone", "ASHRAE 62.1 Vbz = Rp·Pz + Ra·Az", "Plant selection with N+1 redundancy", "Duct main and riser sizing", "ISO 7730 PMV/PPD"],
    inputs: ["Envelope & internal gains", "Climate design data", "Occupancy"],
    outputs: ["Peak loads", "Plant schedule", "Duct sizes", "Comfort indices"],
    standards: ["ASHRAE 62.1-2022", "ASHRAE 55-2023", "ASHRAE 90.1-2022"],
    handoffs: [{ to: "electrical", what: "Mechanical electrical loads" }, { to: "architecture", what: "Plant & riser areas" }, { to: "bim", what: "Duct geometry" }],
    buyers: ["MEP consultancies", "Mechanical contractors", "Facility owners"],
    valueProp: "Right-sized plant and space allocation before architecture is frozen.",
    resultKeys: ["hvac"], limits: "Peak-load method, not hourly simulation.",
  },
  {
    id: "electrical", name: "Electrical", discipline: "Electrical", tier: "Professional",
    tagline: "Load schedules, transformers, cables, protection, renewables and backup power.",
    description: "Builds the load schedule with demand factors; sizes transformers, the main switchboard and sub-mains (ampacity, grouping and voltage drop); computes fault level; sizes PV, battery storage, EV charging and the standby generator.",
    skills: ["Demand-factor load schedule", "Transformer & switchboard sizing", "Cable sizing by ampacity and voltage drop (≤ 3 %)", "Prospective fault current", "PV yield, BESS and EV load management", "Generator sizing for life-safety & standby"],
    inputs: ["Building loads", "Mechanical loads", "Parking spaces"],
    outputs: ["Load schedule", "Single-line ratings", "Cable schedule", "Renewables & backup sizing"],
    standards: ["NEC 2023 (Art. 210, 215, 220, 450, 625, 690, 700, 706)", "BS 7671", "AS/NZS 3000"],
    handoffs: [{ to: "cost", what: "Electrical quantities" }, { to: "sustainability", what: "PV generation" }],
    buyers: ["Electrical engineers", "EV-charging operators", "Owners pursuing electrification"],
    valueProp: "Utility applications and electrification plans grounded in real load numbers.",
    resultKeys: ["electrical"], limits: "Simplified diversity; not an arc-flash or coordination study.",
  },
  {
    id: "hydraulic", name: "Hydraulic", discipline: "Hydraulics", tier: "Professional",
    tagline: "Water, drainage, pumps, hot water, rainwater and greywater.",
    description: "Fixture counts, WSFU/DFU, peak flow, pipe sizing, pressure zoning, booster pumps, stacks and drains, hot-water storage, rainwater harvesting and greywater reuse.",
    skills: ["Fixture provisioning", "Hunter-curve peak flow", "Hazen-Williams pipe sizing", "Pressure zoning & booster sizing", "Hot-water storage & heater sizing", "Rainwater yield & greywater offset"],
    inputs: ["Occupancy", "Height", "Rainfall"],
    outputs: ["Fixture schedule", "Pipe & pump sizes", "Reuse potential"],
    standards: ["IPC 2024", "BS EN 806", "AS/NZS 3500"],
    handoffs: [{ to: "bim", what: "Pipe geometry" }, { to: "cost", what: "Plumbing quantities" }],
    buyers: ["Hydraulic consultants", "Plumbing contractors", "Water-conscious owners"],
    valueProp: "Pressure zoning and pumping decided before the core is fixed.",
    resultKeys: ["hydraulics"], limits: "Simplified diversity curves.",
  },
  {
    id: "fire", name: "Fire Engineering", discipline: "Fire", tier: "Professional",
    tagline: "Egress, construction type, sprinklers and evacuation modelling.",
    description: "Occupant load, exit count, stair capacity, travel distance, construction type & fire-resistance ratings, sprinklers, standpipes, fire-service lifts and smoke control; SFPE hydraulic evacuation model with phased strategy for high-rise and smoke-filling ASET.",
    skills: ["IBC §1004–1017 egress checks", "Construction type & height (Tables 504.3/601)", "NFPA 13 hazard & density", "SFPE hydraulic evacuation model", "Smoke-layer filling ASET vs RSET", "Auto-resolution: adds/widens stairs"],
    inputs: ["Occupancy & floor plate", "Core layout", "Height & material"],
    outputs: ["Egress design", "FRR schedule", "Evacuation curve", "ASET/RSET"],
    standards: ["IBC 2024", "NFPA 13/14/72", "Approved Document B", "NCC Vol One Part D/E"],
    handoffs: [{ to: "architecture", what: "Stairs & core requirements" }],
    buyers: ["Fire engineers", "Architects", "Authorities having jurisdiction"],
    valueProp: "Life-safety layout locked in early, avoiding costly core redesign.",
    resultKeys: ["fire"], limits: "Simplified smoke model; performance designs need CFD (e.g. FDS).",
  },
  {
    id: "facade", name: "Façade Engineering", discipline: "Façade", tier: "Professional",
    tagline: "Mullions, glass, anchors, thermal bridges, condensation and façade fire risk.",
    description: "Sizes mullions and glass for C&C pressures, computes anchor loads, ψ-value thermal bridging, condensation (fRsi), water-test pressure and flags combustible façades.",
    skills: ["Mullion deflection & stress (L/175 ≤ 19 mm)", "Glass plate stress", "Effective U with ψ-values", "fRsi condensation check", "Façade fire screening (NFPA 285 / UK Reg 7(2))"],
    inputs: ["Wind pressures", "Façade type, WWR, U-values"],
    outputs: ["Mullion & glass selection", "Thermal performance", "Fire risk"],
    standards: ["AAMA TIR-A11 / 501.1", "BS EN ISO 13788", "IBC §1402.5"],
    handoffs: [{ to: "physics", what: "Effective U-values" }, { to: "cost", what: "Façade areas & panels" }],
    buyers: ["Façade consultants", "Curtain-wall fabricators", "Developers"],
    valueProp: "Façade cost and risk understood at concept stage.",
    resultKeys: ["facade"], limits: "No 2D/3D thermal modelling of details.",
  },
  {
    id: "physics", name: "Building Physics & Energy", discipline: "Sustainability", tier: "Professional",
    tagline: "Daylight, glare, acoustics, comfort and annual energy.",
    description: "Average daylight factor, glare risk, natural-ventilation feasibility, façade sound insulation, overheating; annual and monthly energy by end use, PV offset and scenario comparison.",
    skills: ["Littlefair average daylight factor", "Façade Rw requirement", "Degree-day annual energy model", "Monthly energy profile", "Scenario comparison (façade, heat pumps, WWR, code baseline)"],
    inputs: ["Envelope", "HVAC results", "Climate"],
    outputs: ["Daylight & acoustics", "EUI", "Scenarios", "Operational carbon"],
    standards: ["ASHRAE 90.1 App. G (proxy)", "Approved Document L", "EN 16798-1"],
    handoffs: [{ to: "sustainability", what: "Operational carbon" }],
    buyers: ["Sustainability consultants", "ESG-driven owners", "Certification teams (LEED/BREEAM/Green Star)"],
    valueProp: "Energy targets tested against design options before they become expensive.",
    resultKeys: ["physics", "energy"], limits: "Degree-day method, not hourly simulation (EnergyPlus).",
  },
  {
    id: "sustainability", name: "Carbon & Resilience", discipline: "Sustainability", tier: "Professional",
    tagline: "Embodied carbon by element and system, plus climate-risk screening.",
    description: "A1–A5 embodied carbon from quantities, carbon by structural system, lower-carbon options; hazard register (heat, flood, storm, wildfire, earthquake, grid outage) and redundancy assessment.",
    skills: ["Quantity-based LCA (A1–A5)", "System-level carbon comparison", "Future-climate cooling margin", "Hazard exposure × vulnerability scoring", "Redundancy review"],
    inputs: ["Quantities", "Hazards", "Plant configuration"],
    outputs: ["kgCO₂e/m²", "Carbon hotspots", "Resilience score & mitigations"],
    standards: ["EN 15978 modules", "LETI / SE 2050 benchmarks"],
    handoffs: [{ to: "ve", what: "Carbon targets for alternatives" }],
    buyers: ["ESG teams", "Lenders & green-bond issuers", "Developers with net-zero commitments"],
    valueProp: "Embodied-carbon reporting and climate-risk disclosure from the design model.",
    resultKeys: ["cost", "resilience"], limits: "Generic carbon factors; replace with product EPDs for certification.",
  },
  {
    id: "accessibility", name: "Accessibility", discipline: "Architecture", tier: "Starter",
    tagline: "Routes, lifts, gradients and accessible facilities.",
    description: "Checks clear widths, corridor widths, ramp gradients and landings, lift provision, accessible egress, WCs and parking.",
    skills: ["ADA 2010 §403–405, 407, 604", "IBC §1009 accessible means of egress", "Parking provision (§208.2)"],
    inputs: ["Corridors, stairs, lifts", "Site level difference", "Parking"],
    outputs: ["Accessibility checklist with PASS/FAIL"],
    standards: ["ADA 2010", "IBC Ch. 11", "Approved Document M", "AS 1428.1"],
    handoffs: [{ to: "codes", what: "Accessibility findings" }],
    buyers: ["Architects", "Public-sector owners", "Access consultants"],
    valueProp: "Avoids late, expensive accessibility retrofits.",
    resultKeys: ["accessibility"], limits: "Building-level checks; room-level detailing not modelled.",
  },
  {
    id: "civil", name: "Civil & Stormwater", discipline: "Civil", tier: "Professional",
    tagline: "Roof and site drainage, detention and rainwater reuse.",
    description: "Rational-method design flows, roof drains and overflows, on-site detention volume and rainwater harvesting yield.",
    skills: ["Rational method Q = C·i·A", "Primary & secondary roof drainage", "Detention sizing", "Rainwater harvesting"],
    inputs: ["Rainfall intensity & annual rainfall", "Roof area"],
    outputs: ["Drain count & sizes", "Detention volume", "Harvest yield"],
    standards: ["IPC §1106/1108", "BS EN 12056-3", "AS/NZS 3500.3"],
    handoffs: [{ to: "hydraulic", what: "Rainwater supply for flushing" }],
    buyers: ["Civil engineers", "Municipal reviewers"],
    valueProp: "Stormwater compliance and reuse sized from day one.",
    resultKeys: ["hydraulics"], limits: "Roof catchment only; site grading not modelled.",
  },
  {
    id: "bim", name: "BIM Coordination", discipline: "BIM", tier: "Professional",
    tagline: "Authors an openBIM IFC4 model and finds physical and semantic clashes.",
    description: "Generates architecture, structure, MEP and fire elements from sized engineering outputs; detects hard clashes and semantic issues (valve access, maintenance clearance, penetrations through lateral elements, fire dampers, riser space, wet services over switchrooms); exports IFC4; auto-syncs issues each run.",
    skills: ["Parametric IFC element authoring", "AABB clash detection with typical-floor grouping", "Semantic clash rules", "IFC4 STEP export (validated with IfcOpenShell)", "Issue tracking with auto-resolution"],
    inputs: ["Scheme & sized systems"],
    outputs: ["IFC4 model", "Clash groups", "Issues/RFIs"],
    standards: ["ISO 16739 (IFC4)", "buildingSMART openBIM"],
    handoffs: [{ to: "construction", what: "Element-to-activity links (4D)" }, { to: "cost", what: "Element volumes" }],
    buyers: ["BIM managers", "General contractors", "Owners requiring openBIM deliverables"],
    valueProp: "Coordination problems found before drawings, not on site.",
    resultKeys: ["bim", "clashes"], limits: "Box geometry (LOD 200); not a replacement for authored LOD 300+ models.",
  },
  {
    id: "cost", name: "Cost & BOQ", discipline: "Commercial", tier: "Starter",
    tagline: "Quantity take-off, bill of quantities and a full cost plan.",
    description: "Measures quantities from the model and sized systems, builds a MasterFormat-coded BOQ with location-factored rates, and adds preliminaries, contingency, fees and escalation; reports by discipline, system and floor; CSV export.",
    skills: ["Model-based QTO", "MasterFormat BOQ", "Location factors", "Cost by discipline / floor / system", "Budget variance"],
    inputs: ["Quantities", "Location", "Budget"],
    outputs: ["BOQ", "Cost plan", "Cost per m²"],
    standards: ["CSI MasterFormat", "NRM-style elemental reporting"],
    handoffs: [{ to: "ve", what: "Cost baseline" }, { to: "construction", what: "Resource-loaded cost (5D)" }],
    buyers: ["Quantity surveyors / cost consultants", "Developers", "Contractors (estimating)"],
    valueProp: "A defensible cost plan the moment the scheme changes.",
    resultKeys: ["cost"], limits: "Generic unit rates; calibrate with local market data.",
  },
  {
    id: "ve", name: "Value Engineering", discipline: "Commercial", tier: "Professional",
    tagline: "Proposes cheaper or lower-carbon alternatives and proves they still work.",
    description: "Generates alternatives (PT slabs, WWR, GGBS, concrete grade, façade type, grid, heat pumps, lift count), re-runs the full engine for each and rejects any that break drift, compliance, energy or carbon.",
    skills: ["Alternative generation", "Full re-analysis per alternative", "Performance-consequence detection", "Cost/carbon trade-off"],
    inputs: ["Baseline design & cost"],
    outputs: ["Ranked VE options with consequences"],
    standards: ["SAVE International VE job plan (method)"],
    handoffs: [{ to: "cost", what: "Recommended savings" }],
    buyers: ["Developers", "Contractors (bid optimisation)", "Owner's representatives"],
    valueProp: "Savings that do not come back as change orders or failed inspections.",
    resultKeys: ["ve"], limits: "Explores a predefined option set.",
  },
  {
    id: "construction", name: "Construction Planning", discipline: "Construction", tier: "Professional",
    tagline: "Sequencing, critical path, 4D/5D, cranes, temporary works and constructability.",
    description: "Builds the activity network and CPM schedule, links model elements to activities (4D), resource-loads cost (5D S-curve), selects tower cranes for the critical lift, designs temporary works (retention, dewatering, back-propping, formwork) and flags constructability issues.",
    skills: ["CPM forward/backward pass", "4D element linking", "5D cash flow", "Crane selection by critical lift", "Temporary-works selection & propping check", "Constructability rules"],
    inputs: ["Scheme", "Foundation", "Cost plan"],
    outputs: ["Gantt & critical path", "Cash flow", "Crane & logistics plan", "Temporary works", "Constructability log"],
    standards: ["CPM scheduling practice", "BS 5975 (temporary works, reference)"],
    handoffs: [{ to: "cost", what: "Escalation & preliminaries timing" }],
    buyers: ["General contractors", "Construction managers", "Developers (financing)"],
    valueProp: "Programme and logistics risk visible at bid stage.",
    resultKeys: ["construction"], limits: "Template-based activity network; not resource-levelled.",
  },
  {
    id: "operations", name: "Digital Twin & Operations", discipline: "Operations", tier: "Enterprise",
    tagline: "Asset health, predictive maintenance and operational optimisation.",
    description: "Maintains the asset register; predicts 90-day failure probability and remaining useful life (Weibull adjusted by condition and runtime); detects anomalies; recommends schedule, set-point and ventilation optimisations.",
    skills: ["Weibull reliability & RUL", "Risk = P(fail) × criticality", "Sensor anomaly detection", "Energy vs baseline", "Optimisation recommendations"],
    inputs: ["Asset register", "Sensor/BMS feeds"],
    outputs: ["Asset health", "Maintenance plan", "Savings opportunities"],
    standards: ["ISO 55000 (asset management, reference)"],
    handoffs: [{ to: "physics", what: "Measured vs design EUI" }],
    buyers: ["Facility managers", "REITs & portfolio owners", "Hospitals & universities"],
    valueProp: "Fewer breakdowns and lower energy bills across the portfolio.",
    resultKeys: [], limits: "Demo uses synthetic sensor data; connect BMS/IoT feeds in production.",
  },
  {
    id: "verifier", name: "Independent Verifier", discipline: "QA", tier: "Starter",
    tagline: "Re-derives key results by a second method so nobody has to trust a black box.",
    description: "Checks equilibrium, Rayleigh vs eigen periods, statics vs FE, Boussinesq vs 2:1 settlement, BIM volumes vs QTO, BOQ arithmetic, energy balance and CPM closure, with tolerances and PASS/WARN/FAIL.",
    skills: ["Global equilibrium", "Rayleigh-quotient period", "Statics cross-checks", "Alternative stress distribution", "Quantity reconciliation", "Schedule closure"],
    inputs: ["All agent results"],
    outputs: ["Verification report"],
    standards: ["Engineering QA practice"],
    handoffs: [{ to: "all", what: "Discrepancies for engineer review" }],
    buyers: ["Engineering QA/QC leads", "Checking engineers", "Insurers"],
    valueProp: "Auditable confidence in AI-assisted engineering — the key to selling to regulated buyers.",
    resultKeys: ["verification"], limits: "Verifies consistency, not the professional judgement of a licensed engineer.",
  },
];

export const agentById = (id: string) => AGENTS.find((a) => a.id === id);

export const PLANS: { tier: Tier; price: string; unit: string; for: string; includes: string[] }[] = [
  { tier: "Starter", price: "$490", unit: "per seat / month", for: "Architects, developers and small consultancies doing feasibility", includes: ["Intake, Architecture, Code Intelligence, Accessibility, Cost & BOQ, Verifier", "Up to 10 active projects", "Compliance & BOQ CSV export", "Email support"] },
  { tier: "Professional", price: "$1,900", unit: "per seat / month", for: "Engineering consultancies and design-build contractors", includes: ["All 22 design & construction agents", "Unlimited projects, IFC4 export, 4D/5D", "Design alternatives & value engineering", "API access (5,000 runs/month)", "Claude assistant"] },
  { tier: "Enterprise", price: "From $60k", unit: "per year", for: "Large consultancies, contractors, owners and portfolios", includes: ["Digital Twin & Operations", "SSO, audit log, data residency, private deployment", "Custom code libraries & rate books", "Volume API, white-label, SLA", "Dedicated success engineer"] },
];
