// Go-to-market playbook: where and how to sell the agents to businesses.
// Channel requirements and fees change — verify each programme's current
// terms before applying.

export interface Channel {
  name: string; type: "Marketplace" | "Platform partner" | "Cloud marketplace" | "AI ecosystem" | "Direct" | "Partners" | "Events" | "Public sector";
  url?: string; who: string; howToSell: string; packageAs: string; agents: string[]; effort: "Low" | "Medium" | "High"; timeToRevenue: string;
}

export const CHANNELS: Channel[] = [
  { name: "Direct sales to engineering consultancies", type: "Direct", who: "Multidisciplinary engineering & architecture firms (structural, MEP, façade, fire, sustainability teams)", howToSell: "Founder-led demos on the firm's own past project; a 4–6 week paid pilot on one live scheme; expand by discipline seats.", packageAs: "Professional seats + API runs", agents: ["structural", "seismic", "wind", "hvac", "electrical", "fire", "codes", "verifier"], effort: "High", timeToRevenue: "2–6 months" },
  { name: "Direct sales to contractors & design-builders", type: "Direct", who: "General contractors, design-build and pre-construction / estimating teams", howToSell: "Lead with bid-stage value: VE, foundation choice, cranes, programme and BOQ in days. Price per tender or per project.", packageAs: "Per-project licence or Professional seats for pre-construction", agents: ["cost", "ve", "construction", "foundation", "bim"], effort: "High", timeToRevenue: "2–6 months" },
  { name: "Developers, owners & owner's reps", type: "Direct", who: "Real-estate developers, REITs, hospitals, universities, public owners", howToSell: "Feasibility-as-a-service: compare sites and massing options on cost, carbon and area before appointing consultants; later upsell the digital twin.", packageAs: "Feasibility reports per site + Enterprise operations", agents: ["intake", "architecture", "cost", "sustainability", "operations"], effort: "Medium", timeToRevenue: "1–4 months" },
  { name: "Autodesk App Store / Autodesk Platform Services", type: "Platform partner", url: "https://apps.autodesk.com", who: "Revit, AutoCAD and Autodesk Construction Cloud users", howToSell: "Publish a Revit add-in or ACC integration that sends the model/brief to the agents API and returns results; list it on the App Store; join the Autodesk developer network.", packageAs: "Add-in (free) + paid API subscription", agents: ["bim", "structural", "codes", "cost"], effort: "Medium", timeToRevenue: "3–9 months" },
  { name: "Procore App Marketplace", type: "Marketplace", url: "https://marketplace.procore.com", who: "General contractors and owners running projects in Procore", howToSell: "Build a Procore integration that pushes issues/RFIs, schedule and BOQ into Procore; apply as a technology partner and list the app.", packageAs: "Construction & cost agents as an integrated app", agents: ["construction", "cost", "bim", "ve"], effort: "Medium", timeToRevenue: "3–9 months" },
  { name: "Bentley iTwin ecosystem", type: "Platform partner", url: "https://developer.bentley.com", who: "Infrastructure owners and digital-twin programmes", howToSell: "Expose the operations and verification agents as an iTwin-connected service; join Bentley's developer/partner programme.", packageAs: "Digital-twin analytics (Enterprise)", agents: ["operations", "verifier", "sustainability"], effort: "High", timeToRevenue: "6–12 months" },
  { name: "Trimble / Graphisoft / Nemetschek ecosystems", type: "Platform partner", who: "Tekla, Trimble Connect, Archicad and Allplan users (strong in Europe & APAC)", howToSell: "IFC-based connector (the engine already exports validated IFC4) plus an add-on listing in each vendor's partner/add-on programme.", packageAs: "openBIM connector + API", agents: ["bim", "structural", "facade"], effort: "Medium", timeToRevenue: "6–12 months" },
  { name: "AWS / Azure / Google Cloud marketplaces", type: "Cloud marketplace", url: "https://aws.amazon.com/marketplace", who: "Enterprise buyers who prefer to buy through existing cloud commitments", howToSell: "List the SaaS (and a private-deployment option) as a marketplace offer; private offers let enterprises buy against committed cloud spend.", packageAs: "Enterprise annual contract / metered API", agents: ["all"], effort: "Medium", timeToRevenue: "3–6 months after first enterprise lead" },
  { name: "Claude & MCP ecosystem", type: "AI ecosystem", who: "Businesses already using Claude (Claude Code, Claude apps, Claude API) for engineering work", howToSell: "Ship the included Claude Skill and an MCP server that wraps /api/v1; list it in MCP server registries and connector directories (check each directory's current submission process); charge for the API key.", packageAs: "Skill + MCP connector (free) → paid API key", agents: ["all"], effort: "Low", timeToRevenue: "1–3 months" },
  { name: "Resellers, BIM consultancies & system integrators", type: "Partners", who: "Autodesk/Bentley resellers, BIM consultancies, digital-transformation integrators", howToSell: "20–30 % reseller margin or referral fee; give them a white-label workspace and demo projects; they bundle it with training and implementation.", packageAs: "White-label Enterprise", agents: ["all"], effort: "Medium", timeToRevenue: "4–9 months" },
  { name: "Industry events & communities", type: "Events", who: "AEC technology leaders and early adopters", howToSell: "Speak and demo at events such as Autodesk University, ENR FutureTech, Greenbuild and CTBUH conferences; publish validation case studies; run webinars with a design firm customer.", packageAs: "Lead generation for direct sales", agents: ["all"], effort: "Medium", timeToRevenue: "Pipeline in 1–3 months" },
  { name: "Permitting authorities & public sector", type: "Public sector", who: "Plan-review departments and governments adopting BIM-based e-submission", howToSell: "Offer automated clause-level pre-checks and verification reports to applicants or reviewers; respond to govtech tenders, usually with an integrator partner.", packageAs: "Code Intelligence + Verifier as a pre-check service", agents: ["codes", "accessibility", "fire", "verifier"], effort: "High", timeToRevenue: "9–18 months" },
  { name: "Insurers, lenders & ESG data buyers", type: "Direct", who: "Property insurers, construction lenders, green-bond and ESG analysts", howToSell: "Sell portfolio-level seismic, flood/heat-resilience and embodied-carbon screening as reports or data feeds via API.", packageAs: "Per-asset screening reports / data API", agents: ["seismic", "sustainability", "geotech", "verifier"], effort: "Medium", timeToRevenue: "3–9 months" },
];

export const SEGMENTS: { segment: string; pain: string; offer: string; agents: string[]; buyer: string }[] = [
  { segment: "Engineering consultancies", pain: "Scheme-stage design is slow; fee pressure; coordination churn between disciplines.", offer: "Multidisciplinary scheme in a day with clause-level compliance and verification.", agents: ["structural", "seismic", "wind", "hvac", "electrical", "fire", "codes", "verifier"], buyer: "Discipline directors, digital/innovation lead" },
  { segment: "Contractors (pre-construction)", pain: "Bids priced on incomplete designs; VE that later fails; crane and programme risk.", offer: "Tender-stage BOQ, VE with proof, foundation choice, CPM and cranes.", agents: ["cost", "ve", "construction", "foundation", "bim"], buyer: "Pre-construction director, chief estimator" },
  { segment: "Developers & owners", pain: "Committing to sites and massing before costs, carbon and risk are known.", offer: "Site feasibility comparisons, budget and carbon certainty, later a digital twin.", agents: ["intake", "architecture", "cost", "sustainability", "operations"], buyer: "Development manager, head of design" },
  { segment: "Facility & portfolio managers", pain: "Reactive maintenance and energy waste.", offer: "Predictive maintenance and operational optimisation.", agents: ["operations"], buyer: "Head of FM, energy manager" },
  { segment: "Regulators & insurers", pain: "Manual plan review; poor visibility of physical risk.", offer: "Automated pre-checks, verification reports, risk screening.", agents: ["codes", "verifier", "seismic", "sustainability"], buyer: "Chief building official, risk/underwriting lead" },
];

export const READINESS: { item: string; why: string }[] = [
  { item: "Position as decision support, sealed by a licensed engineer", why: "Software cannot take engineer-of-record responsibility; say so in contracts, UI and reports." },
  { item: "Professional / technology E&O insurance", why: "Enterprise buyers and channel partners will ask for it before signing." },
  { item: "Terms of service, DPA and acceptable-use policy", why: "Required by every marketplace and enterprise procurement team." },
  { item: "Security: SSO, audit log, encryption, SOC 2 Type II roadmap", why: "Large consultancies and contractors run security questionnaires." },
  { item: "Validation pack", why: "Publish benchmark comparisons (closed-form tests, a past project re-analysed) — the Verifier agent's output is the core of this." },
  { item: "Code-text licensing", why: "Reference clause numbers only; do not reproduce copyrighted code text without a licence from the publisher." },
  { item: "Data residency & private deployment option", why: "Public-sector, defence and many EU/APAC buyers require it." },
  { item: "Calibrated rate books & carbon factors per market", why: "Local cost and EPD data turns a demo into a trusted estimate." },
];

export const LAUNCH_PLAN: { phase: string; weeks: string; actions: string[] }[] = [
  { phase: "1. Prove", weeks: "Weeks 1–4", actions: ["Re-run 2–3 real past projects with friendly firms and publish the comparison", "Record a 5-minute demo per segment", "Set up API keys, usage metering and billing (e.g. Stripe)"] },
  { phase: "2. Pilot", weeks: "Weeks 5–10", actions: ["Sign 3–5 paid pilots (one consultancy, one contractor, one developer)", "Ship the Claude Skill + MCP connector and list them", "Start the Autodesk or Procore integration based on pilot demand"] },
  { phase: "3. Scale", weeks: "Weeks 11–24", actions: ["Convert pilots to annual contracts and case studies", "Launch marketplace listings (Autodesk/Procore, then AWS/Azure)", "Recruit 2–3 reseller/integrator partners in your home region"] },
];
