/**
 * Thin client for the *optional* ClipForge AI backend.
 *
 * The app is fully usable without a backend — these calls are enhancements:
 *   - captionIdeas(): on-topic hook ideas generated by Claude (falls back to a
 *     built-in list when the backend or its API key is unavailable).
 *   - transcribe(): speech-to-text for auto-captions (Whisper on the backend).
 *
 * Base URL comes from VITE_AI_API_BASE; in dev it defaults to '' and relies on
 * the Vite proxy (see vite.config.ts) forwarding /api to the FastAPI server.
 */

const BASE = import.meta.env.VITE_AI_API_BASE ?? ''

const BUILTIN_IDEAS = [
  'Wait for it…',
  'POV: you finally get it',
  'The part nobody talks about',
  'Save this for later',
  'Watch till the end 👀',
  'This changed everything',
]

export interface CaptionIdeasResult {
  ideas: string[]
  source: 'ai' | 'fallback'
  note?: string
}

export async function captionIdeas(input: {
  topic?: string
  transcript?: string
  platform?: string
}): Promise<CaptionIdeasResult> {
  try {
    const res = await fetch(`${BASE}/api/clipforge/caption-ideas`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        topic: input.topic ?? '',
        transcript: input.transcript ?? '',
        platform: input.platform ?? 'TikTok / Reels / Shorts',
      }),
    })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data = (await res.json()) as CaptionIdeasResult
    if (!Array.isArray(data.ideas) || !data.ideas.length) throw new Error('empty')
    return data
  } catch {
    return {
      ideas: BUILTIN_IDEAS,
      source: 'fallback',
      note: 'AI service unavailable — showing built-in ideas. Run the backend with an ANTHROPIC_API_KEY for custom hooks.',
    }
  }
}

export interface TranscribeResult {
  text: string
}

/** Returns the transcript, or throws an Error with a user-safe message. */
export async function transcribe(file: File): Promise<TranscribeResult> {
  const form = new FormData()
  form.append('file', file)

  let res: Response
  try {
    res = await fetch(`${BASE}/api/clipforge/transcribe`, { method: 'POST', body: form })
  } catch {
    throw new Error(
      'Could not reach the transcription service. Start the backend, or set VITE_AI_API_BASE.',
    )
  }

  if (res.status === 501) {
    throw new Error(
      'Transcription is not configured on the backend. Add an OPENAI_API_KEY (or an in-browser Whisper model) to enable it.',
    )
  }
  if (!res.ok) {
    let detail = ''
    try {
      detail = (await res.json())?.detail ?? ''
    } catch {
      /* ignore */
    }
    throw new Error(detail || 'Transcription failed. Please try a standard MP4 or WebM file.')
  }
  return (await res.json()) as TranscribeResult
}
