"""Generate the agent organisation from architecture/org.json (single source of truth).

- creates agent files that org.json names but that do not exist yet (staff and new specialists)
- writes a managed block (between ORG-START / ORG-END) into every bld-* agent: role, reporting line,
  sub-specialty checklist, division rules, and the mandatory return format for specialists
- renders architecture/ORG.md
Run:  python architecture/tools/build_org.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARCH = ROOT / "architecture"
AGENTS = ROOT / ".claude" / "agents"
ORG = json.loads((ARCH / "org.json").read_text())
START, END = "<!-- ORG-START (generated by architecture/tools/build_org.py; edit org.json, not this block) -->", "<!-- ORG-END -->"
PROTO = "Follow `architecture/PROTOCOL.md`: evidence tags, source ranking, analysis hierarchy, verification, never invent site data, hazard values, prices or code clauses, and state what you did not check. Outputs are feasibility-stage aids, not certified design."

NEW_SPECIALISTS = {
 "bld-energy-modeller": ("Building energy modeller: turns architectural geometry into an EnergyPlus model, runs annual simulations, and feeds results to the optimisation and HVAC agents. Use for energy use, peak loads, overheating or design-option energy comparisons.", "sonnet",
  "Inputs: IFC or massing geometry, constructions from `architecture/data/materials.csv`, schedules from the brief, HVAC concept from `bld-mechanical-hvac`, weather file for the site.\nMethod: EnergyPlus (skill `bld-building-physics`). Verify geometry areas against the IFC, U-values against hand calculation, and a shoebox model against a hand heat balance before trusting the full model."),
 "bld-optimisation-agent": ("Optimisation agent: compares design options and searches design spaces (GA, Bayesian, gradient, topology, multi-objective, Monte Carlo, parametric) against objectives with safety and code limits as hard constraints. Use whenever a 'best' design is chosen numerically or options A-E are compared.", "opus",
  "Inputs: option set or parameterised model, objectives with senses, hard constraints from `bld-constraint-manager`.\nMethod: filter infeasible options first, then `architecture/tools/pareto.py` for option sets and pymoo for searches (skill `bld-optimisation-pymoo`); cross-check optima by brute force or several seeds; report active constraints and margin."),
 "bld-independent-verifier": ("Independent verification agent (Agent B): recalculates a governing result by a different method without seeing the original numbers, then runs the automated comparison (Agent C, verify_compare.py) to decide PROCEED or INVESTIGATE. Use for every governing structural, seismic, geotechnical, fire or energy result before it is relied on.", "opus",
  "Rules: you receive the problem statement and inputs, never Agent A's results; use a different method (hand calculation vs FE, numpy vs OpenSees, alternative formula); write your results as JSON {name: value}; run `python architecture/tools/verify_compare.py a.json b.json --tol tol.json`. A PROCEED is recorded; an INVESTIGATE goes back to the division with both calculations. Agreement of two agents using the same wrong input is not verification: check inputs independently too."),
 "bld-results-interpreter": ("Simulation results interpreter: reads OpenSees, CalculiX, EnergyPlus or CFD outputs and checks them for plausibility (units, equilibrium, convergence, mode shapes, energy balance, sensitivity) before anyone uses them. Use after every simulation run.", "sonnet",
  "Method: compare against closed-form or simplified results, check reactions equal loads, effective masses sum to 1, periods and drifts are physically plausible, warnings and non-convergence are reported, and results change smoothly with mesh or time step. Flag anything implausible as a FAILED CHECK rather than explaining it away."),
}
STAFF_BODY = """Inputs: the request, `architecture/org.json`, `architecture/memory/`, the latest brief and report.
Output: a short structured note to `bld-director` with your section of the plan, explicit UNKNOWNs, and anything that needs a human decision. You do not perform engineering calculations; you organise the work so specialists can."""


def fm(name, desc, tools, model):
    return f"---\nname: {name}\ndescription: {desc}\ntools: {tools}\nmodel: {model}\n---\n\n"


def ensure_files():
    created = []
    for name, role, purpose in ORG["director"]["staff"]:
        p = AGENTS / f"{name}.md"
        if not p.exists():
            p.write_text(fm(name, f"{role} on the Chief Engineering Director's staff. {purpose} Use when the director needs this orchestration step.", "Read, Grep, Glob, Bash, Write, Edit", "sonnet") + PROTO + "\n\n" + STAFF_BODY + "\n")
            created.append(name)
    for name, (desc, model, body) in NEW_SPECIALISTS.items():
        p = AGENTS / f"{name}.md"
        if not p.exists():
            p.write_text(fm(name, desc, "Read, Grep, Glob, Bash, Write, Edit, WebSearch, WebFetch", model) + PROTO + "\n\n" + body + "\n")
            created.append(name)
    return created


def return_format_block(fire=False):
    lines = ["## Mandatory return format", "Return exactly these ten sections, in this order, each non-empty (write `None` if nothing applies). Validate with `python architecture/tools/validate_return.py <file>" + (" --fire" if fire else "") + "`.", "```", *ORG["return_format"], "```"]
    if fire:
        lines.append("RESULTS must state one verdict per check: " + " / ".join(ORG["fire_verdicts"]) + ". Never 'probably safe'.")
    return "\n".join(lines)


def blocks():
    out = {}
    staff = {s[0]: s for s in ORG["director"]["staff"]}
    for name, (n, role, purpose) in staff.items():
        out[name] = f"**Role:** {role} (Chief Engineering Director's staff). **Reports to:** `bld-director`.\n\n{purpose}"
    for lead, desc in ORG["leads"].items():
        out[lead] = f"**Role:** {desc} **Reports to:** `bld-director`. Divisions led: " + ", ".join(f"{d['n']} {d['name']}" for d in ORG["divisions"] if d["lead"] == lead and "engine" not in d) + "."
    for d in ORG["divisions"]:
        if "engine" in d:
            continue
        fire = d["agent"] == "bld-fire-life-safety"
        b = [f"**Role:** Division {d['n']}, {d['name']}. **Reports to:** `{d['lead']}`." + (" **Support:** " + ", ".join(f"`{s}`" for s in d.get("support", [])) + "." if d.get("support") else "")]
        engines = [e for e in ORG["divisions"] if "engine" in e and e["agent"] == d["agent"]]
        b.append("## Sub-specialties (the director runs you with `focus: <one or more of these>`)\n" + "\n".join("- " + s for s in d["subs"]))
        for e in engines:
            b.append(f"## Engine: {e['engine']}\n" + "\n".join("- " + s for s in e["subs"]) + "\n\n" + e.get("rules", ""))
        if d.get("rules"):
            b.append("## Division rules\n" + d["rules"])
        b.append(return_format_block(fire))
        out.setdefault(d["agent"], "")
        out[d["agent"]] = (out[d["agent"]] + "\n\n" if out[d["agent"]] else "") + "\n\n".join(b)
    for sup, lead in ORG["support_only"].items():
        if sup not in out:
            out[sup] = f"**Role:** support specialist. **Reports to:** `{lead}`.\n\n" + return_format_block()
    return out


def write_blocks():
    bl = blocks()
    for name, text in bl.items():
        p = AGENTS / f"{name}.md"
        s = p.read_text()
        s = re.sub(r"^\*\*Role:\*\*.*\n\n?", "", s, flags=re.M)                       # older hand-written role lines
        s = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?", "", s, flags=re.S)
        head, body = s.split("---\n", 2)[1], s.split("---\n", 2)[2]
        s = "---\n" + head + "---\n\n" + START + "\n" + text.strip() + "\n" + END + "\n" + body.lstrip("\n")
        p.write_text(s)
    return bl


def render_md(write: bool = True) -> str:
    D = ORG["divisions"]
    L = ["# Engineering organisation", "", "Generated from `org.json` by `tools/build_org.py`. Do not edit by hand.", "",
         "```", "                         CHIEF ENGINEERING DIRECTOR (bld-director)",
         "        staff: requirements · task planning · routing · dependencies · iteration ·",
         "               constraints · decisions · conflicts · memory · deliverables",
         "                ┌───────────────────────┼───────────────────────┐",
         "        bld-project-lead        bld-design-lead        bld-safety-qa-lead",
         "                └───────────────────────┼───────────────────────┘",
         f"                     {len([d for d in D if 'engine' not in d])} DIVISIONS (specialist agents, focus by sub-specialty)", "```", "",
         "**Dispatch constraint.** In Claude Code only the main-session agent can launch agents. Run `claude --agent bld-director`; the director launches staff, leads and specialists. Leads and staff plan and integrate; they do not launch agents themselves.", "",
         "## Director's staff", "| Agent | Role | Job |", "|---|---|---|"]
    L += [f"| `{a}` | {r} | {p} |" for a, r, p in ORG["director"]["staff"]]
    L += ["", "## Leads", "| Agent | Scope |", "|---|---|"] + [f"| `{k}` | {v} |" for k, v in ORG["leads"].items()]
    L += ["", "## Divisions", "| # | Division | Agent | Lead | Support | Sub-specialties |", "|---|---|---|---|---|---|"]
    for d in D:
        L.append(f"| {d['n']} | {d['name']} | " + (f"engine: {d['engine']}" if "engine" in d else f"`{d['agent']}`") + f" | `{d['lead']}` | " + ", ".join(f"`{s}`" for s in d.get("support", [])) + f" | {len(d['subs'])} |")
    L += ["", "## Every specialist returns", "```", *ORG["return_format"], "```",
          "Checked by `tools/validate_return.py` (fire returns also need a verdict: " + " / ".join(ORG["fire_verdicts"]) + ").", "",
          "## Requirement source classes (Codes division)", ", ".join(ORG["source_classes"]), "",
          "## Pipelines", "- **Earthquake:** seismic agent → OpenSees model → simulation → results interpreter → independent verifier + `verify_compare.py` (reference: `seismic/pipeline.py`).",
          "- **Energy:** architect → geometry → energy modeller → EnergyPlus → optimisation agent → architect + HVAC (EnergyPlus not installed here).",
          "- **Verification:** engineer A → solution; verifier B → independent method; `verify_compare.py` (C) → PROCEED or INVESTIGATE.",
          "- **Options:** architecture generates A..E for named objectives → constraint manager filters → optimisation agent (`tools/pareto.py`, pymoo) → decision manager → human decision.", ""]
    text = "\n".join(L)
    if write:
        (ARCH / "ORG.md").write_text(text)
    return text


if __name__ == "__main__":
    c = ensure_files(); b = write_blocks(); render_md()
    print("created", c); print("managed blocks", len(b))
