"use client";

import { Loader2, Printer } from "lucide-react";
import { useEffect, useState } from "react";
import type { BimModel } from "@/lib/engine/bim";
import { api, Button, Segmented } from "./ui";

type Sheet = "plan" | "section" | "elevation" | "rcp";

function TitleBlock({ x, y, w, title, code, scale, no }: { x: number; y: number; w: number; title: string; code: string; scale: string; no: string }) {
  return (
    <g fontSize={9} fill="#0f172a">
      <rect x={x} y={y} width={w} height={44} fill="#fff" stroke="#0f172a" strokeWidth={0.8} />
      <line x1={x + w * 0.55} y1={y} x2={x + w * 0.55} y2={y + 44} stroke="#0f172a" strokeWidth={0.5} />
      <text x={x + 8} y={y + 16} fontWeight={700} fontSize={11}>{title}</text>
      <text x={x + 8} y={y + 32} fill="#475569">{code} · Generated by Chimera AEC · not for construction</text>
      <text x={x + w * 0.55 + 8} y={y + 16}>Scale {scale}</text>
      <text x={x + w * 0.55 + 8} y={y + 32}>Sheet {no}</text>
    </g>
  );
}

export function Drawings({ projectId, code }: { projectId: string; code: string }) {
  const [model, setModel] = useState<BimModel | null>(null);
  const [sheet, setSheet] = useState<Sheet>("plan");
  const [level, setLevel] = useState(1);
  const [err, setErr] = useState("");
  useEffect(() => { api<BimModel>(`/api/projects/${projectId}/model`).then(setModel).catch((e) => setErr((e as Error).message)); }, [projectId]);
  if (err) return <p className="text-sm text-slate-500">{err}</p>;
  if (!model) return <div className="flex h-96 items-center justify-center text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading model…</div>;

  const els = model.elements;
  const Lx = Math.max(...els.filter((e) => e.ifc === "IfcSlab").map((e) => e.box.dx));
  const Ly = Math.max(...els.filter((e) => e.ifc === "IfcSlab").map((e) => e.box.dy));
  const H = model.levels[model.levels.length - 1].z;
  const floors = model.levels.length - 1;
  const lv = Math.min(level, floors - 1);
  const W = 900, Hh = 620, m = 60;
  const sPlan = Math.min((W - 2 * m) / Lx, (Hh - 2 * m - 50) / Ly);
  const X = (x: number) => m + x * sPlan, Y = (y: number) => m + (Ly - y) * sPlan;
  const atLevel = els.filter((e) => e.level === lv);
  const gx = model.grids.filter((g) => g.axis === "x"), gy = model.grids.filter((g) => g.axis === "y");

  const plan = (
    <g>
      {gx.map((g) => <g key={`x${g.name}`}><line x1={X(g.at)} x2={X(g.at)} y1={Y(Ly) - 22} y2={Y(0) + 10} stroke="#94a3b8" strokeDasharray="8 3 2 3" strokeWidth={0.6} /><circle cx={X(g.at)} cy={Y(Ly) - 30} r={8} fill="#fff" stroke="#0f172a" strokeWidth={0.7} /><text x={X(g.at)} y={Y(Ly) - 27} fontSize={8} textAnchor="middle">{g.name}</text></g>)}
      {gy.map((g) => <g key={`y${g.name}`}><line y1={Y(g.at)} y2={Y(g.at)} x1={X(0) - 22} x2={X(Lx) + 10} stroke="#94a3b8" strokeDasharray="8 3 2 3" strokeWidth={0.6} /><circle cx={X(0) - 30} cy={Y(g.at)} r={8} fill="#fff" stroke="#0f172a" strokeWidth={0.7} /><text x={X(0) - 30} y={Y(g.at) + 3} fontSize={8} textAnchor="middle">{g.name}</text></g>)}
      <rect x={X(0)} y={Y(Ly)} width={Lx * sPlan} height={Ly * sPlan} fill="none" stroke="#0f172a" strokeWidth={2.2} />
      {atLevel.filter((e) => sheet === "rcp" ? ["MEC", "FIR", "PLB", "ELE"].includes(e.discipline) || e.ifc === "IfcColumn" || e.ifc === "IfcWall" : e.discipline === "STR" || e.discipline === "ARC").filter((e) => e.ifc !== "IfcSlab" && e.ifc !== "IfcPlate").map((e) => {
        const fill = e.ifc === "IfcColumn" ? "#0f172a" : e.ifc === "IfcWall" ? "#334155" : e.ifc === "IfcStair" ? "none" : e.ifc === "IfcBeam" ? "none" : e.discipline === "MEC" ? "#eb683455" : e.discipline === "FIR" ? "#e34948aa" : e.discipline === "PLB" ? "#1baf7a99" : e.discipline === "ELE" ? "#eda10099" : "none";
        const stroke = e.ifc === "IfcBeam" ? "#64748b" : e.ifc === "IfcStair" ? "#0f172a" : "none";
        return <rect key={e.id} x={X(e.box.x)} y={Y(e.box.y + e.box.dy)} width={Math.max(0.6, e.box.dx * sPlan)} height={Math.max(0.6, e.box.dy * sPlan)} fill={fill} stroke={stroke} strokeWidth={0.6} strokeDasharray={e.ifc === "IfcBeam" ? "4 2" : undefined} />;
      })}
      {sheet === "plan" && atLevel.filter((e) => e.ifc === "IfcStair").map((e) => Array.from({ length: 10 }, (_, i) => <line key={e.id + i} x1={X(e.box.x + (e.box.dx * i) / 10)} x2={X(e.box.x + (e.box.dx * i) / 10)} y1={Y(e.box.y)} y2={Y(e.box.y + e.box.dy)} stroke="#94a3b8" strokeWidth={0.4} />))}
      {els.filter((e) => e.ifc === "IfcTransportElement").map((e) => <g key={e.id}><rect x={X(e.box.x)} y={Y(e.box.y + e.box.dy)} width={e.box.dx * sPlan} height={e.box.dy * sPlan} fill="none" stroke="#0f172a" strokeWidth={0.6} /><line x1={X(e.box.x)} y1={Y(e.box.y)} x2={X(e.box.x + e.box.dx)} y2={Y(e.box.y + e.box.dy)} stroke="#0f172a" strokeWidth={0.4} /><line x1={X(e.box.x)} y1={Y(e.box.y + e.box.dy)} x2={X(e.box.x + e.box.dx)} y2={Y(e.box.y)} stroke="#0f172a" strokeWidth={0.4} /></g>)}
      <g fontSize={8} fill="#334155">
        <line x1={X(0)} x2={X(Lx)} y1={Y(0) + 28} y2={Y(0) + 28} stroke="#334155" strokeWidth={0.6} />
        {gx.map((g) => <line key={g.name} x1={X(g.at)} x2={X(g.at)} y1={Y(0) + 24} y2={Y(0) + 32} stroke="#334155" strokeWidth={0.6} />)}
        {gx.slice(1).map((g, i) => <text key={g.name} x={(X(g.at) + X(gx[i].at)) / 2} y={Y(0) + 25} textAnchor="middle">{Math.round((g.at - gx[i].at) * 1000)}</text>)}
        <text x={X(Lx / 2)} y={Y(0) + 44} textAnchor="middle" fontWeight={600}>{Math.round(Lx * 1000)} overall</text>
      </g>
    </g>
  );

  const sSec = Math.min((W - 2 * m) / Lx, (Hh - 2 * m - 50) / H);
  const SX = (x: number) => m + x * sSec, SZ = (z: number) => Hh - m - 50 - z * sSec;
  const midY = Ly / 2;
  const section = (
    <g>
      <line x1={SX(-3)} x2={SX(Lx + 3)} y1={SZ(0)} y2={SZ(0)} stroke="#0f172a" strokeWidth={1.5} />
      {els.filter((e) => e.discipline === "STR" && (sheet === "elevation" ? e.ifc === "IfcSlab" : e.box.y <= midY && e.box.y + e.box.dy >= midY - 0.1)).map((e) => (
        <rect key={e.id} x={SX(e.box.x)} y={SZ(e.box.z + e.box.dz)} width={Math.max(0.5, e.box.dx * sSec)} height={Math.max(0.5, e.box.dz * sSec)} fill={e.ifc === "IfcSlab" ? "#475569" : e.ifc === "IfcWall" ? "#94a3b8" : "#cbd5e1"} stroke="#0f172a" strokeWidth={0.3} />
      ))}
      {sheet === "elevation" && els.filter((e) => e.ifc === "IfcPlate" && e.name.startsWith("Façade S")).map((e) => {
        const wwr = Number(e.props?.wwr ?? 0.5);
        return <g key={e.id}><rect x={SX(e.box.x)} y={SZ(e.box.z + e.box.dz)} width={e.box.dx * sSec} height={e.box.dz * sSec} fill="#e2e8f0" stroke="#64748b" strokeWidth={0.3} /><rect x={SX(e.box.x + 0.1)} y={SZ(e.box.z + e.box.dz * (0.15 + wwr * 0.85))} width={(e.box.dx - 0.2) * sSec} height={e.box.dz * wwr * 0.85 * sSec} fill="#bcdaff" stroke="#2a78d6" strokeWidth={0.3} /></g>;
      })}
      {sheet === "section" && els.filter((e) => e.discipline === "MEC" && e.box.y <= midY + 3 && e.box.y + e.box.dy >= midY - 3 && e.ifc === "IfcDuctSegment" && e.box.dz < 2).map((e) => <rect key={e.id} x={SX(e.box.x)} y={SZ(e.box.z + e.box.dz)} width={e.box.dx * sSec} height={e.box.dz * sSec} fill="#eb6834" fillOpacity={0.5} />)}
      {model.levels.map((l) => <g key={l.index} fontSize={8}><line x1={SX(Lx) + 6} x2={SX(Lx) + 40} y1={SZ(l.z)} y2={SZ(l.z)} stroke="#0f172a" strokeWidth={0.5} /><text x={SX(Lx) + 44} y={SZ(l.z) + 3}>{l.name} +{l.z.toFixed(2)}</text></g>).filter((_, i) => floors < 25 || i % Math.ceil(floors / 20) === 0 || i === floors)}
    </g>
  );
  const sheetNo = { plan: "A-101", rcp: "M-101", section: "A-301", elevation: "A-201" }[sheet];
  const title = { plan: `General arrangement plan — ${model.levels[lv].name}`, rcp: `Coordinated services plan — ${model.levels[lv].name}`, section: "Building section A–A", elevation: "South elevation" }[sheet];
  return (
    <div>
      <div className="mb-3 flex flex-wrap items-center gap-3">
        <Segmented value={sheet} onChange={setSheet} options={[{ value: "plan", label: "Floor plan" }, { value: "rcp", label: "Services plan" }, { value: "section", label: "Section" }, { value: "elevation", label: "Elevation" }]} />
        {(sheet === "plan" || sheet === "rcp") && <label className="flex items-center gap-2 text-xs text-slate-600">Level <input type="range" min={0} max={floors - 1} value={lv} onChange={(e) => setLevel(+e.target.value)} className="accent-brand-600" /><span className="num">{model.levels[lv].name}</span></label>}
        <Button size="sm" variant="secondary" className="ml-auto" onClick={() => window.print()}><Printer className="h-3.5 w-3.5" />Print</Button>
      </div>
      <div className="overflow-x-auto rounded-xl bg-white ring-1 ring-slate-200">
        <svg viewBox={`0 0 ${W} ${Hh}`} style={{ minWidth: 640, width: "100%" }} role="img" aria-label={title}>
          <rect x={8} y={8} width={W - 16} height={Hh - 16} fill="none" stroke="#0f172a" strokeWidth={1} />
          {sheet === "plan" || sheet === "rcp" ? plan : section}
          <g transform={`translate(${W - 70} 40)`}><circle r={14} fill="none" stroke="#0f172a" strokeWidth={0.7} /><path d="M0 -12 L5 6 L0 2 L-5 6 Z" fill="#0f172a" /><text y={-18} fontSize={9} textAnchor="middle">N</text></g>
          <TitleBlock x={W - 420} y={Hh - 60} w={410} title={title} code={code} scale="1:200 @ A1" no={sheetNo} />
        </svg>
      </div>
    </div>
  );
}
